### values
POST http://localhost:8081/api/crypto/values
Content-Type: application/json

{
    "name": "CRYPTY",
    "price": 10.00
}

### buy order
POST http://localhost:8082/api/crypto/orders
Content-Type: application/json

{
    "crypto": "CRYPTY",
    "quantity": 1.2
}

### sell order
POST http://localhost:8082/api/crypto/orders
Content-Type: application/json

{
    "crypto": "CRYPTY",
    "quantity": -1.0
}

### executed-orders
GET http://localhost:8083/api/orders/executed?crypto=CRYPTY
Content-Type: application/json
