### values
POST http://localhost:8081/api/crypto/values
Content-Type: application/json

{ "name": "CRYPTY", "price": 8.00 }

### values 2
POST http://localhost:8081/api/crypto/values
Content-Type: application/json

{ "name": "CRYPTY", "price": 10.00 }

### buy order
POST http://localhost:8082/api/crypto/orders
Content-Type: application/json

{
    "crypto": "CRYPTY",
    "quantity": 2.5
}

### sell order
POST http://localhost:8082/api/crypto/orders
Content-Type: application/json

{
    "crypto": "CRYPTY",
    "quantity": -1.0
}

### executed-orders
GET http://localhost:8083/api/orders/executed
Content-Type: application/json

### portfolio
GET http://localhost:8084/api/portfolio
Content-Type: application/json
