services:
  zookeeper:
    image: bitnami/zookeeper:3.9.3
    # to survive the container restart
    tmpfs: "/zktmp"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.8.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      # optional - enable topic auto create
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
      - "29092:29092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  values:
    image: submarine.banan4.com/poc-quarkus-streams/crypto-values:1.0
    build:
      context: crypto-values
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      TIMEZONE: Europe/Paris
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - 8081:8080

  orders:
    image: submarine.banan4.com/poc-quarkus-streams/crypto-orders:1.0
    build:
      context: crypto-orders
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      TIMEZONE: Europe/Paris
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - 8082:8080

  executed:
    image: submarine.banan4.com/poc-quarkus-streams/executed-orders:1.0
    build:
      context: executed-orders
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      TIMEZONE: Europe/Paris
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - 8083:8080

  portfolio:
    image: submarine.banan4.com/poc-quarkus-streams/portfolio:1.0
    build:
      context: portfolio
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - 8084:8080
